// apps/app/src/routes/settings/assistant/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { assistantsCollection, modelsCollection, providersCollection } from "$lib/data";
  import { getUrlQueryParam } from "$lib/util.svelte";
  import { eq, useLiveQuery } from "@tanstack/svelte-db";

  let id = $derived(getUrlQueryParam("id"));

  let modelsQuery = useLiveQuery((q) =>
    q
      .from({ provider: providersCollection })
      .innerJoin({ model: modelsCollection }, ({ provider, model }) =>
        eq(provider.id, model.providerId),
      ),
  );

  let model = $state("");
</script>

<p>{id}</p>

{#if modelsQuery.data}
  <form
    onsubmit={async (e) => {
      e.preventDefault();
      await assistantsCollection.update(id, (draft) => {
        draft.modelId = model;
      }).isPersisted.promise;

      await goto(`/?assistant=${id}`);
    }}
  >
    <select class="select" bind:value={model}>
      {#each modelsQuery.data as { provider, model }}
        <option value={model.id}>{provider?.name} - {model?.name}</option>
      {/each}
    </select>
    <button class="btn btn-primary" type="submit">保存</button>
  </form>
{/if}

// apps/app/src/routes/assistant.tsx
import { useAssistantMutation, useAssistantQuery } from "#data/Assistant.ts";
import { useModelsQuery } from "#data/Model.ts";
import { createFileRoute } from "@tanstack/solid-router";
import { For, Show } from "solid-js";
import * as v from "valibot";

export const Route = createFileRoute("/assistant")({
  validateSearch: v.object({
    id: v.pipe(v.string(), v.uuid()),
  }),
  component: RouteComponent,
});

function RouteComponent() {
  const assistantId = Route.useSearch({ select: (search) => search.id });

  const assistant = useAssistantQuery(assistantId);
  const models = useModelsQuery();
  const mutation = useAssistantMutation();

  let modelSelect: HTMLSelectElement;

  return (
    <Show when={assistant.isSuccess && assistant.data}>
      {(assistant) => (
        <div>
          <p>{assistant().name}</p>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              const modelId = modelSelect.value;
              mutation.mutate({
                ...assistant(),
                modelId: modelId ? modelId : null,
              });
            }}
          >
            <select class="input" ref={(e) => (modelSelect = e)}>
              <option value="" selected={assistant().modelId === null}>
                &lt;无&gt;
              </option>
              <For each={models.data}>
                {(model) => (
                  <option value={model.id} selected={assistant().modelId === model.id}>
                    {model.name}
                  </option>
                )}
              </For>
            </select>

            <button class="btn-primary" type="submit">
              保存设置
            </button>
          </form>
        </div>
      )}
    </Show>
  );
}
